version: "3.9"

services:
    site:
        build: .
        image: conjurer/flow-decision-records.org:latest
        command: bundle exec jekyll serve --trace --host 0.0.0.0 --watch --incremental --port 4005
        environment:
            - JEKYLL_ENV=development
        volumes:
            - ./:/srv/jekyll
        ports:
            - 4005:4005
